name: twist2
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ampl-asl=1.0.0
  - assimp=5.4.2
  - blas=2.304
  - blas-devel=3.11.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - casadi=3.6.5
  - cffi=1.17.0
  - console_bridge=1.0.2
  - eigen=3.4.0
  - eigenpy=3.8.0
  - h2=4.1.0
  - hpack=4.0.0
  - hpp-fcl=2.4.5
  - hyperframe=6.0.1
  - icu=73.2
  - ipopt=3.14.16
  - ld_impl_linux-64=2.45
  - libblas=3.11.0
  - libboost=1.86.0
  - libboost-devel=1.86.0
  - libboost-headers=1.86.0
  - libboost-python=1.86.0
  - libboost-python-devel=1.86.0
  - libcblas=3.11.0
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.11.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libosqp=0.6.3
  - libqdldl=0.1.7
  - libscotch=7.0.4
  - libspral=2024.05.08
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - metis=5.1.0
  - mumps-include=5.7.3
  - mumps-seq=5.7.3
  - ncurses=6.5
  - octomap=1.9.8
  - openblas=0.3.30
  - openssl=3.6.0
  - packaging=25.0
  - pinocchio=3.2.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - pooch=1.8.2
  - proxsuite=0.6.7
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.8.20
  - python_abi=3.8
  - qhull=2020.2
  - qhull-static=2020.2
  - readline=8.2
  - setuptools=75.3.0
  - simde=0.8.2
  - tinyxml2=10.0.0
  - tk=8.6.13
  - urdfdom=4.0.1
  - urdfdom_headers=1.1.2
  - urllib3=2.2.3
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aioice==0.9.0
      - aiortc==1.9.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - arm-pytorch-utilities==0.4.3
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autograd==1.7.0
      - av==12.3.0
      - avp-stream==2.2.2
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - blinker==1.8.2
      - certifi==2025.11.12
      - charset-normalizer==3.3.2
      - click==8.1.8
      - coloredlogs==15.0.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.1.1
      - cryptography==46.0.3
      - customtkinter==5.2.2
      - cycler==0.12.1
      - darkdetect==0.8.0
      - dash==3.3.0
      - decorator==5.2.1
      - dill==0.4.0
      - dnspython==2.6.1
      - einops==0.8.1
      - etils==1.3.0
      - eval-type-backport==0.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.16.1
      - flask==3.0.3
      - flatbuffers==25.9.23
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - google-crc32c==1.5.0
      - grpcio==1.70.0
      - grpcio-tools==1.70.0
      - h5py==3.11.0
      - hiredis==3.3.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.11
      - ifaddr==0.2.0
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipdb==0.13.13
      - ipython==8.12.3
      - ipywidgets==8.1.8
      - isaacgym-stubs==1.1rc4
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.7
      - lxml==6.0.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - mujoco==3.2.3
      - mujoco-python-viewer==0.1.4
      - narwhals==1.42.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.13.0
      - nlopt==2.7.1
      - numpy==1.23.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxruntime-gpu==1.19.2
      - open3d==0.19.0
      - opencv-python==4.12.0.88
      - pandas==2.0.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - plotly==6.5.1
      - prompt-toolkit==3.0.52
      - protobuf==5.29.5
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==3.0.1
      - pybind11-stubgen==2.5.5
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydelatin==0.2.8
      - pydub==0.25.1
      - pyee==13.0.0
      - pyfqmr==0.5.0
      - pygments==2.19.2
      - pylibsrtp==0.10.0
      - pyopengl==3.1.10
      - pyopenssl==25.3.0
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pyrealsense2==2.55.1.6486
      - python-dateutil==2.9.0.post0
      - pytorch-kinematics==0.7.6
      - pytorch-seed==0.2.0
      - pyttsx3==2.99
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - redis==6.1.1
      - referencing==0.35.1
      - requests==2.32.4
      - retrying==1.4.2
      - rich==14.2.0
      - rpds-py==0.20.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==2.47.0
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.13.3
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tomli==2.3.0
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - wandb==0.23.1
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.15
      - wuji-retargeting==0.1.0
      - wujihandpy==1.4.0
      - zipp==3.20.2
      - zmq==0.0.0
prefix: /home/heng/miniconda3/envs/twist2
